### ISSUE TITLE
about research

### ISSUE THREAD

**Issue by liuguozhe** [NKAI-Decision-Team/LLM-PySC2#1]
This is so cool! May I ask how long this project has been in development? Will there be further in-depth research in the future?

**Comment by 734162621** [comment]
Thanks! We started research for LLM decision-making in about March 2024 and started the LLM-PySC2 project in July. As you can see in README.md, we will continue to update the environment and add more features to improve it. We will also start a new round of method research after the environment is fully functional and stable enough. [flowers~]
